[package]
name = "sensoreval"
version = "0.1.0"
authors = ["Michael Zimmermann <sigmaepsilon92@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
serde = "1.0.99"
serde-pickle = "0.5.0"
serde_derive = "1.0.99"
serde_ignored = "0.1.0"
bincode = "1.1.4"
toml = "0.5.3"
cairo-sys-rs = "0.9.0"

[dependencies.cairo-rs]
version = "0.7.1"
features = ["png"]

[dependencies.nalgebra]
version = "0.18.0"
features = ["serde-serialize"]
