[workspace]
members = [
    "kalman",
    "math",
    "sensoreval",
    "sensoreval_graphics",
    "sensoreval_gui",
    "sensoreval_psim",
    "sensoreval_psim_macros",
    "sensoreval_utils",
    "testlib",
]

[profile.dev]
opt-level = 1

[profile.release]
debug = 2