[package]
name = "sensoreval"
version = "0.1.0"
authors = ["Michael Zimmermann <sigmaepsilon92@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde-pickle = "0.5"
serde_ignored = "0.1"
bincode = "1.2"
toml = "0.5"
cairo-sys-rs = "0.9"
cairo-rs = { version = "0.7", features = ["png"] }
nalgebra = { version = "0.18", features = ["serde-serialize"] }

[profile.dev]
opt-level = 1
