[package]
name = "sensoreval"
version = "0.1.0"
authors = ["Michael Zimmermann <sigmaepsilon92@gmail.com>"]
edition = "2018"

[dependencies]
kalman = { path = "../kalman" }
math = { path = "../math" }
sensoreval_gui = { path = "../sensoreval_gui" }
sensoreval_graphics = { path = "../sensoreval_graphics" }
sensoreval_psim = { path = "../sensoreval_psim" }
sensoreval_utils = { path = "../sensoreval_utils" }

approx = "0.3"
bincode = "1.3"
blas-src = { version = "*", features = ["openblas"] }
cairo-rs = "0.8.0"
clap = "2.33"
enum_dispatch = "0.3"
eom = { git = "https://github.com/M1cha/eom", branch = "master" }
half = { version = "1.6", features = ["serde"] }
lapack-src = { version = "*", features = ["openblas"] }
librsvg = { git = "https://gitlab.gnome.org/GNOME/librsvg" }
nalgebra = "0.22"
ndarray = { version = "0.13", features = ["serde"] }
ndarray-linalg = "0.12"
num-traits = "0.2"
openblas-src = { version = "*", features = ["static"] }
pango = "0.8"
rand = "0.7"
regex = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_ignored = "0.1"
serde_json = "1.0"
serde-pickle = "0.6"
thiserror = "1.0"
toml = "0.5"