[package]
name = "sensoreval_macros"
version = "0.1.0"
authors = ["Michael Zimmermann <sigmaepsilon92@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
convert_case = "^0.4"
proc-macro2 = "^1.0"
proc-macro-error = "^1.0"
syn = "1.0"
quote = "1.0"
