name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy
    - uses: actions/checkout@v2
    - name: apt update
      run: sudo apt-get update
    - name: Install Dependencies
      run: sudo apt-get install libpango1.0-dev qtbase5-dev qtdeclarative5-dev qtmultimedia5-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy -- -D warnings
    - name: Check codestyle (rust)
      run: cargo fmt -- --check
    - name: Check codestyle (cargo)
      run: |
        cargo install cargo-sort
        cargo sort -w --check
